settings:
  legacy:
    force: true
    interval: 500ms
schema:
- name: api
  path: /home/vagrant/go/src/github.com/fluidkeys/api
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
