language: go

go:
  - "1.10.x"
  - master

addons:
  postgresql: "9.6"

script: TEST_DATABASE_URL="postgres://postgres:@localhost:5432/travis" make test

notifications:
    email: false

env:
  global:
    - DISABLE_SEND_EMAIL=1
