language: go

go:
  - "1.10.x"
  - master

before_install:
  - go get -u github.com/golang/dep/cmd/dep

before_script:
  - psql -c 'create database travis;' -U postgres

script: TEST_DATABASE_URL="postgres://postgres:@localhost:5432/travis" make test

notifications:
    email: false
