language: go

go:
  - "1.10.x"
  - master

addons:
  postgresql: "9.6"

before_install:
  - go get -u github.com/golang/dep/cmd/dep

script: TEST_DATABASE_URL="postgres://postgres:@localhost:5432/travis" make test

notifications:
    email: false
