#!/bin/sh -eux

LOCAL_PSQL="psql"
HEROKU_PSQL="heroku pg:psql"

if [ "${MIGRATE_HEROKU:-0}" -eq "1" ]; then
	PSQL_COMMAND=${HEROKU_PSQL}
else
	PSQL_COMMAND=${LOCAL_PSQL}
fi

for sqlfile in $@; do
	$PSQL_COMMAND < $sqlfile;
done
